# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='school_name',
            new_name='course_name',
        ),
    ]
