# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170402_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
