# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170402_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=5000),
        ),
    ]
